import { StyleSheet } from "@react-pdf/renderer"

export const pdfStyles = StyleSheet.create({
  page: {
    flexDirection: "column",
    backgroundColor: "#ffffff",
    padding: 20,
    fontFamily: "NotoSansArabic",
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 20,
    borderBottom: 2,
    borderBottomColor: "#223152",
    paddingBottom: 10,
    textTransform: "capitalize",
  },
  logo: {
    width: 120,
    height: 70,
  },
  headerCenter: {
    flex: 1,
    alignItems: "center",
    marginHorizontal: 20,
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#223152",
    marginBottom: 5,
  },
  headerSubtitle: {
    fontSize: 14,
    color: "#223152",
    marginBottom: 3,
  },
  schoolInfo: {
    alignItems: "flex-end",
    fontSize: 12,
    color: "#223152",
  },
  studentInfo: {
    marginBottom: 15,
    padding: 10,
    backgroundColor: "#f1f5f9",
    borderRadius: 5,
  },
  studentName: {
    fontSize: 16,
    fontWeight: "bold",
    color: "#223152",
    marginBottom: 5,
  },
  studentId: {
    fontSize: 12,
    color: "#64748b",
  },
  gradeReference: {
    marginBottom: 15,
    padding: 10,
    backgroundColor: "#f8f9fa",
    borderRadius: 5,
  },
  gradeReferenceTitle: {
    fontSize: 14,
    fontWeight: "bold",
    marginBottom: 10,
    color: "#223152",
  },
  gradeReferenceGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
  },
  gradeReferenceItem: {
    flexDirection: "row",
    alignItems: "center",
    width: "48%",
    marginBottom: 5,
  },
  gradeColorBox: {
    width: 12,
    height: 12,
    marginRight: 5,
  },
  gradeText: {
    fontSize: 10,
  },
  horizontalTable: {
    display: "flex",
    flexDirection: "column",
    width: "100%",
    marginBottom: 20,
  },
  tableRow: {
    flexDirection: "row",
    borderBottomWidth: 1,
    borderBottomColor: "#e5e7eb",
  },
  tableHeader: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#223152",
    color: "white",
    padding: "8px 6px",
    lineHeight: "1.5",
    fontSize: 10,
    fontWeight: "bold",
    textAlign: "center",
    flex: 1,
    borderRightWidth: 1,
    borderRightColor: "#ffffff",
  },
  tableCell: {
    padding: "2px",
    fontSize: 10,
    textAlign: "center",
    flex: 1,
    borderRightWidth: 1,
    borderRightColor: "#e5e7eb",
  },
  tableCellWithIndicator: {
    padding: 8,
    fontSize: 10,
    textAlign: "center",
    flex: 1,
    borderRightWidth: 1,
    borderRightColor: "#e5e7eb",
    position: "relative",
  },
  gradeIndicator: {
    position: "absolute",
    left: 0,
    top: 0,
    bottom: 0,
    width: 4,
  },
  footer: {
    position: "absolute",
    bottom: 30,
    left: 20,
    right: 20,
    flexDirection: "row",
    justifyContent: "space-between",
    borderTop: 1,
    borderTopColor: "#223152",
    paddingTop: 10,
  },
  footerText: {
    fontSize: 12,
    color: "#223152",
  },
})
